# Generated by Django 5.1.4 on 2025-01-09 08:27

import notes_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(default=notes_app.models.generate_pk, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
